//  disconnetWallet
export const HOME_INITIALIZE_BEGIN = 'HOME_INITIALIZE_BEGIN';
export const HOME_INITIALIZE_SUCCESS = 'HOME_INITIALIZE_SUCCESS';
export const HOME_INITIALIZE_FAILURE = 'HOME_INITIALIZE_FAILURE';