import BigNumber from "bignumber.js";

export const pools = [
  {
    name: 'eth/usdt lp',
    earnedToken: 'iETH/USDT',
    token: 'ETH/USDT',
    poolsInfoToken: 'eth-usdt',
    pricePerFullShare: 1,
    tokenLogoList: ["WETH", "USDT"],
    canDepositTokenList: ["eth/usdt lp", "eth", "weth", "usdt"],
    canDepositTokenAllowanceList: Array(4).fill(new BigNumber(0)),
    fetchApprovalPending: Array(4).fill(false),
    tokenDepositFunctionList: ["deposit", "depositETH", "depositToken0", "depositToken1"],
    tokenDepositAllFunctionList: ["depositAll", null, "depositToken0All", "depositToken1All"],
    fetchDepositPending: Array(4).fill(false),
    canWithdrawTokenList: ["eth/usdt lp", "eth", "weth", "usdt"],
    tokenWithdrawFunctionList: ["withdraw", "withdrawETH", "withdrawToken0", "withdrawToken1"],
    tokenWithdrawAllFunctionList: ["withdrawAll", "withdrawETHAll", "withdrawToken0All", "withdrawToken1All"],
    fetchWithdrawPending: Array(4).fill(false),
    contractAddress: "0x7E43210a4c6831D421f57026617Fdfc8ED3A0baf",
    pricePerFullShare: 0,
    pairPriceToken: '0xc509f486e551eeb6e18e7c4e1fbb8ba0348d131c',
    pairPrice: '0',
  },
  {
    name: 'eth/dai lp',
    earnedToken: 'iETH/DAI',
    token: 'ETH/DAI',
    poolsInfoToken: 'eth-dai',
    pricePerFullShare: 1,
    tokenLogoList: ["WETH", "DAI"],
    canDepositTokenList: ["eth/dai lp", "eth", "dai", "weth"],
    canDepositTokenAllowanceList: Array(4).fill(new BigNumber(0)),
    fetchApprovalPending: Array(4).fill(false),
    tokenDepositFunctionList: ["deposit", "depositETH", "depositToken0", "depositToken1"],
    tokenDepositAllFunctionList: ["depositAll", null, "depositToken0All", "depositToken1All"],
    fetchDepositPending: Array(4).fill(false),
    canWithdrawTokenList: ["eth/dai lp", "eth", "weth", "dai"],
    tokenWithdrawFunctionList: ["withdraw", "withdrawETH", "withdrawToken0", "withdrawToken1"],
    tokenWithdrawAllFunctionList: ["withdrawAll", "withdrawETHAll", "withdrawToken0All", "withdrawToken1All"],
    fetchWithdrawPending: Array(4).fill(false),
    contractAddress: "0x19d994471D61d36FE367928Cc58102a376089D1f",
    pricePerFullShare: 0,
    pairPriceToken: '0xc509f486e551eeb6e18e7c4e1fbb8ba0348d131c',
    pairPrice: '0',
  },
  {
    name: 'eth/usdc lp',
    earnedToken: 'iETH/USDC',
    token: 'ETH/USDC',
    poolsInfoToken: 'eth-usdc',
    pricePerFullShare: 1,
    tokenLogoList: ["WETH", "USDC"],
    canDepositTokenList: ["eth/usdc lp", "eth", "usdc", "weth"],
    canDepositTokenAllowanceList: Array(4).fill(new BigNumber(0)),
    fetchApprovalPending: Array(4).fill(false),
    tokenDepositFunctionList: ["deposit", "depositETH", "depositToken0", "depositToken1"],
    tokenDepositAllFunctionList: ["depositAll", null, "depositToken0All", "depositToken1All"],
    fetchDepositPending: Array(4).fill(false),
    canWithdrawTokenList: ["eth/usdc lp", "eth", "weth", "usdc"],
    tokenWithdrawFunctionList: ["withdraw", "withdrawETH", "withdrawToken0", "withdrawToken1"],
    tokenWithdrawAllFunctionList: ["withdrawAll", "withdrawETHAll", "withdrawToken0All", "withdrawToken1All"],
    fetchWithdrawPending: Array(4).fill(false),
    contractAddress: "0x68A23248000d5d4C943EE685989998c1B19bD74E",
    pricePerFullShare: 0,
    pairPriceToken: '0xc509f486e551eeb6e18e7c4e1fbb8ba0348d131c',
    pairPrice: '0',
  },
  {
    name: 'eth/wbtc lp',
    earnedToken: 'iETH/wBTC',
    token: 'ETH/wBTC',
    poolsInfoToken: 'eth-wbtc',
    pricePerFullShare: 1,
    tokenLogoList: ["WETH", "wBTC"],
    canDepositTokenList: ["eth/wbtc lp", "eth", "wbtc", "weth"],
    canDepositTokenAllowanceList: Array(4).fill(new BigNumber(0)),
    fetchApprovalPending: Array(4).fill(false),
    tokenDepositFunctionList: ["deposit", "depositETH", "depositToken0", "depositToken1"],
    tokenDepositAllFunctionList: ["depositAll", null, "depositToken0All", "depositToken1All"],
    fetchDepositPending: Array(4).fill(false),
    canWithdrawTokenList: ["eth/wbtc lp", "eth", "weth", "wbtc"],
    tokenWithdrawFunctionList: ["withdraw", "withdrawETH", "withdrawToken0", "withdrawToken1"],
    tokenWithdrawAllFunctionList: ["withdrawAll", "withdrawETHAll", "withdrawToken0All", "withdrawToken1All"],
    fetchWithdrawPending: Array(4).fill(false),
    contractAddress: "0x68A23248000d5d4C943EE685989998c1B19bD74E",
    pricePerFullShare: 0,
    pairPriceToken: '0xc509f486e551eeb6e18e7c4e1fbb8ba0348d131c',
    pairPrice: '0',
  },
]