export const LIQUIDITY_FETCH_POOLS_INFO_BEGIN = 'LIQUIDITY_FETCH_POOLS_INFO_BEGIN';
export const LIQUIDITY_FETCH_POOLS_INFO_SUCCESS = 'LIQUIDITY_FETCH_POOLS_INFO_SUCCESS';
export const LIQUIDITY_FETCH_POOLS_INFO_FAILURE = 'LIQUIDITY_FETCH_POOLS_INFO_FAILURE';

export const LIQUIDITY_FETCH_BALANCE_BEGIN = 'LIQUIDITY_FETCH_BALANCE_BEGIN';
export const LIQUIDITY_FETCH_BALANCE_SUCCESS = 'LIQUIDITY_FETCH_BALANCE_SUCCESS';
export const LIQUIDITY_FETCH_BALANCE_FAILURE = 'LIQUIDITY_FETCH_BALANCE_FAILURE';

export const LIQUIDITY_FETCH_BALANCES_BEGIN = 'LIQUIDITY_FETCH_BALANCES_BEGIN';
export const LIQUIDITY_FETCH_BALANCES_SUCCESS = 'LIQUIDITY_FETCH_BALANCES_SUCCESS';
export const LIQUIDITY_FETCH_BALANCES_FAILURE = 'LIQUIDITY_FETCH_BALANCES_FAILURE';

export const LIQUIDITY_FETCH_DEPOSIT_BEGIN = 'LIQUIDITY_FETCH_DEPOSIT_BEGIN';
export const LIQUIDITY_FETCH_DEPOSIT_SUCCESS = 'LIQUIDITY_FETCH_DEPOSIT_SUCCESS';
export const LIQUIDITY_FETCH_DEPOSIT_FAILURE = 'LIQUIDITY_FETCH_DEPOSIT_FAILURE';

export const LIQUIDITY_FETCH_WITHDRAW_BEGIN = 'LIQUIDITY_FETCH_WITHDRAW_BEGIN';
export const LIQUIDITY_FETCH_WITHDRAW_SUCCESS = 'LIQUIDITY_FETCH_WITHDRAW_SUCCESS';
export const LIQUIDITY_FETCH_WITHDRAW_FAILURE = 'LIQUIDITY_FETCH_WITHDRAW_FAILURE';

export const LIQUIDITY_CHECK_APPROVAL_BEGIN = 'LIQUIDITY_CHECK_APPROVAL_BEGIN';
export const LIQUIDITY_CHECK_APPROVAL_SUCCESS = 'LIQUIDITY_CHECK_APPROVAL_SUCCESS';
export const LIQUIDITY_CHECK_APPROVAL_FAILURE = 'LIQUIDITY_CHECK_APPROVAL_FAILURE';

export const LIQUIDITY_FETCH_APPROVAL_BEGIN = 'LIQUIDITY_FETCH_APPROVAL_BEGIN';
export const LIQUIDITY_FETCH_APPROVAL_SUCCESS = 'LIQUIDITY_FETCH_APPROVAL_SUCCESS';
export const LIQUIDITY_FETCH_APPROVAL_FAILURE = 'LIQUIDITY_FETCH_APPROVAL_FAILURE';

export const LIQUIDITY_FETCH_FULL_SHARE_BEGIN = 'LIQUIDITY_FETCH_FULL_SHARE_BEGIN';
export const LIQUIDITY_FETCH_FULL_SHARE_SUCCESS = 'LIQUIDITY_FETCH_FULL_SHARE_SUCCESS';
export const LIQUIDITY_FETCH_FULL_SHARE_FAILURE = 'LIQUIDITY_FETCH_FULL_SHARE_FAILURE';

export const LIQUIDITY_FETCH_PAIR_PRICE_OUT_BEGIN = 'LIQUIDITY_FETCH_PAIR_PRICE_OUT_BEGIN';
export const LIQUIDITY_FETCH_PAIR_PRICE_OUT_DONT_REQUEST = 'LIQUIDITY_FETCH_PAIR_PRICE_OUT_DONT_REQUEST';
export const LIQUIDITY_FETCH_PAIR_PRICE_OUT_SUCCESS = 'LIQUIDITY_FETCH_PAIR_PRICE_OUT_SUCCESS';
export const LIQUIDITY_FETCH_PAIR_PRICE_OUT_FAILURE = 'LIQUIDITY_FETCH_PAIR_PRICE_OUT_FAILURE';

// export const LIQUIDITY_FETCH_BALANCE_BEGIN = 'LIQUIDITY_FETCH_BALANCE_BEGIN';
// export const LIQUIDITY_FETCH_BALANCE_SUCCESS = 'LIQUIDITY_FETCH_BALANCE_SUCCESS';
// export const LIQUIDITY_FETCH_BALANCE_FAILURE = 'LIQUIDITY_FETCH_BALANCE_FAILURE';

// export const LIQUIDITY_FETCH_CURRENTLY_STAKED_BEGIN = 'LIQUIDITY_FETCH_CURRENTLY_STAKED_BEGIN';
// export const LIQUIDITY_FETCH_CURRENTLY_STAKED_SUCCESS = 'LIQUIDITY_FETCH_CURRENTLY_STAKED_SUCCESS';
// export const LIQUIDITY_FETCH_CURRENTLY_STAKED_FAILURE = 'LIQUIDITY_FETCH_CURRENTLY_STAKED_FAILURE';

// export const LIQUIDITY_FETCH_REWARDS_AVAILABLE_BEGIN = 'LIQUIDITY_FETCH_REWARDS_AVAILABLE_BEGIN';
// export const LIQUIDITY_FETCH_REWARDS_AVAILABLE_SUCCESS = 'LIQUIDITY_FETCH_REWARDS_AVAILABLE_SUCCESS';
// export const LIQUIDITY_FETCH_REWARDS_AVAILABLE_FAILURE = 'LIQUIDITY_FETCH_REWARDS_AVAILABLE_FAILURE';

// export const LIQUIDITY_FETCH_HALF_TIME_BEGIN = 'LIQUIDITY_FETCH_HALF_TIME_BEGIN';
// export const LIQUIDITY_FETCH_HALF_TIME_SUCCESS = 'LIQUIDITY_FETCH_HALF_TIME_SUCCESS';
// export const LIQUIDITY_FETCH_HALF_TIME_FAILURE = 'LIQUIDITY_FETCH_HALF_TIME_FAILURE';

// export const LIQUIDITY_FETCH_CAN_WITHDRAW_TIME_BEGIN = 'LIQUIDITY_FETCH_CAN_WITHDRAW_TIME_BEGIN';
// export const LIQUIDITY_FETCH_CAN_WITHDRAW_TIME_SUCCESS = 'LIQUIDITY_FETCH_CAN_WITHDRAW_TIME_SUCCESS';
// export const LIQUIDITY_FETCH_CAN_WITHDRAW_TIME_FAILURE = 'LIQUIDITY_FETCH_CAN_WITHDRAW_TIME_FAILURE';

// export const LIQUIDITY_FETCH_APPROVAL_BEGIN = 'LIQUIDITY_FETCH_APPROVAL_BEGIN';
// export const LIQUIDITY_FETCH_APPROVAL_SUCCESS = 'LIQUIDITY_FETCH_APPROVAL_SUCCESS';
// export const LIQUIDITY_FETCH_APPROVAL_FAILURE = 'LIQUIDITY_FETCH_APPROVAL_FAILURE';

// export const LIQUIDITY_FETCH_LIQUIDITY_BEGIN = 'LIQUIDITY_FETCH_LIQUIDITY_BEGIN';
// export const LIQUIDITY_FETCH_LIQUIDITY_SUCCESS = 'LIQUIDITY_FETCH_LIQUIDITY_SUCCESS';
// export const LIQUIDITY_FETCH_LIQUIDITY_FAILURE = 'LIQUIDITY_FETCH_LIQUIDITY_FAILURE';

// export const LIQUIDITY_FETCH_WITHDRAW_BEGIN = 'LIQUIDITY_FETCH_WITHDRAW_BEGIN';
// export const LIQUIDITY_FETCH_WITHDRAW_SUCCESS = 'LIQUIDITY_FETCH_WITHDRAW_SUCCESS';
// export const LIQUIDITY_FETCH_WITHDRAW_FAILURE = 'LIQUIDITY_FETCH_WITHDRAW_FAILURE';

// export const LIQUIDITY_FETCH_CLAIM_BEGIN = 'LIQUIDITY_FETCH_CLAIM_BEGIN';
// export const LIQUIDITY_FETCH_CLAIM_SUCCESS = 'LIQUIDITY_FETCH_CLAIM_SUCCESS';
// export const LIQUIDITY_FETCH_CLAIM_FAILURE = 'LIQUIDITY_FETCH_CLAIM_FAILURE';

