export const FARM_FETCH_POOLS_INFO_BEGIN = 'FARM_FETCH_POOLS_INFO_BEGIN';
export const FARM_FETCH_POOLS_INFO_SUCCESS = 'FARM_FETCH_POOLS_INFO_SUCCESS';
export const FARM_FETCH_POOLS_INFO_FAILURE = 'FARM_FETCH_POOLS_INFO_FAILURE';

export const FARM_CHECK_APPROVAL_BEGIN = 'FARM_CHECK_APPROVAL_BEGIN';
export const FARM_CHECK_APPROVAL_SUCCESS = 'FARM_CHECK_APPROVAL_SUCCESS';
export const FARM_CHECK_APPROVAL_FAILURE = 'FARM_CHECK_APPROVAL_FAILURE';

export const FARM_FETCH_BALANCE_BEGIN = 'FARM_FETCH_BALANCE_BEGIN';
export const FARM_FETCH_BALANCE_SUCCESS = 'FARM_FETCH_BALANCE_SUCCESS';
export const FARM_FETCH_BALANCE_FAILURE = 'FARM_FETCH_BALANCE_FAILURE';

export const FARM_FETCH_CURRENTLY_STAKED_BEGIN = 'FARM_FETCH_CURRENTLY_STAKED_BEGIN';
export const FARM_FETCH_CURRENTLY_STAKED_SUCCESS = 'FARM_FETCH_CURRENTLY_STAKED_SUCCESS';
export const FARM_FETCH_CURRENTLY_STAKED_FAILURE = 'FARM_FETCH_CURRENTLY_STAKED_FAILURE';

export const FARM_FETCH_REWARDS_AVAILABLE_BEGIN = 'FARM_FETCH_REWARDS_AVAILABLE_BEGIN';
export const FARM_FETCH_REWARDS_AVAILABLE_SUCCESS = 'FARM_FETCH_REWARDS_AVAILABLE_SUCCESS';
export const FARM_FETCH_REWARDS_AVAILABLE_FAILURE = 'FARM_FETCH_REWARDS_AVAILABLE_FAILURE';

export const FARM_FETCH_APPROVAL_BEGIN = 'FARM_FETCH_APPROVAL_BEGIN';
export const FARM_FETCH_APPROVAL_SUCCESS = 'FARM_FETCH_APPROVAL_SUCCESS';
export const FARM_FETCH_APPROVAL_FAILURE = 'FARM_FETCH_APPROVAL_FAILURE';

export const FARM_FETCH_STAKE_BEGIN = 'FARM_FETCH_STAKE_BEGIN';
export const FARM_FETCH_STAKE_SUCCESS = 'FARM_FETCH_STAKE_SUCCESS';
export const FARM_FETCH_STAKE_FAILURE = 'FARM_FETCH_STAKE_FAILURE';

export const FARM_FETCH_WITHDRAW_BEGIN = 'FARM_FETCH_WITHDRAW_BEGIN';
export const FARM_FETCH_WITHDRAW_SUCCESS = 'FARM_FETCH_WITHDRAW_SUCCESS';
export const FARM_FETCH_WITHDRAW_FAILURE = 'FARM_FETCH_WITHDRAW_FAILURE';

export const FARM_FETCH_CLAIM_BEGIN = 'FARM_FETCH_CLAIM_BEGIN';
export const FARM_FETCH_CLAIM_SUCCESS = 'FARM_FETCH_CLAIM_SUCCESS';
export const FARM_FETCH_CLAIM_FAILURE = 'FARM_FETCH_CLAIM_FAILURE';

export const FARM_FETCH_EXIT_BEGIN = 'FARM_FETCH_EXIT_BEGIN';
export const FARM_FETCH_EXIT_SUCCESS = 'FARM_FETCH_EXIT_SUCCESS';
export const FARM_FETCH_EXIT_FAILURE = 'FARM_FETCH_EXIT_FAILURE';