//  fetchBalances
export const SWAP_FETCH_BALANCES_BEGIN = 'SWAP_FETCH_BALANCES_BEGIN';
export const SWAP_FETCH_BALANCES_SUCCESS = 'SWAP_FETCH_BALANCES_SUCCESS';
export const SWAP_FETCH_BALANCES_FAILURE = 'SWAP_FETCH_BALANCES_FAILURE';