export const STAKE_FETCH_POOLS_INFO_BEGIN = 'STAKE_FETCH_POOLS_INFO_BEGIN';
export const STAKE_FETCH_POOLS_INFO_SUCCESS = 'STAKE_FETCH_POOLS_INFO_SUCCESS';
export const STAKE_FETCH_POOLS_INFO_FAILURE = 'STAKE_FETCH_POOLS_INFO_FAILURE';

export const STAKE_CHECK_APPROVAL_BEGIN = 'STAKE_CHECK_APPROVAL_BEGIN';
export const STAKE_CHECK_APPROVAL_SUCCESS = 'STAKE_CHECK_APPROVAL_SUCCESS';
export const STAKE_CHECK_APPROVAL_FAILURE = 'STAKE_CHECK_APPROVAL_FAILURE';

export const STAKE_FETCH_BALANCE_BEGIN = 'STAKE_FETCH_BALANCE_BEGIN';
export const STAKE_FETCH_BALANCE_SUCCESS = 'STAKE_FETCH_BALANCE_SUCCESS';
export const STAKE_FETCH_BALANCE_FAILURE = 'STAKE_FETCH_BALANCE_FAILURE';

export const STAKE_FETCH_CURRENTLY_STAKED_BEGIN = 'STAKE_FETCH_CURRENTLY_STAKED_BEGIN';
export const STAKE_FETCH_CURRENTLY_STAKED_SUCCESS = 'STAKE_FETCH_CURRENTLY_STAKED_SUCCESS';
export const STAKE_FETCH_CURRENTLY_STAKED_FAILURE = 'STAKE_FETCH_CURRENTLY_STAKED_FAILURE';

export const STAKE_FETCH_REWARDS_AVAILABLE_BEGIN = 'STAKE_FETCH_REWARDS_AVAILABLE_BEGIN';
export const STAKE_FETCH_REWARDS_AVAILABLE_SUCCESS = 'STAKE_FETCH_REWARDS_AVAILABLE_SUCCESS';
export const STAKE_FETCH_REWARDS_AVAILABLE_FAILURE = 'STAKE_FETCH_REWARDS_AVAILABLE_FAILURE';

export const STAKE_FETCH_HALF_TIME_BEGIN = 'STAKE_FETCH_HALF_TIME_BEGIN';
export const STAKE_FETCH_HALF_TIME_SUCCESS = 'STAKE_FETCH_HALF_TIME_SUCCESS';
export const STAKE_FETCH_HALF_TIME_FAILURE = 'STAKE_FETCH_HALF_TIME_FAILURE';

export const STAKE_FETCH_CAN_WITHDRAW_TIME_BEGIN = 'STAKE_FETCH_CAN_WITHDRAW_TIME_BEGIN';
export const STAKE_FETCH_CAN_WITHDRAW_TIME_SUCCESS = 'STAKE_FETCH_CAN_WITHDRAW_TIME_SUCCESS';
export const STAKE_FETCH_CAN_WITHDRAW_TIME_FAILURE = 'STAKE_FETCH_CAN_WITHDRAW_TIME_FAILURE';