export const STAKE_FETCH_POOLS_INFO_BEGIN = 'STAKE_FETCH_POOLS_INFO_BEGIN';
export const STAKE_FETCH_POOLS_INFO_SUCCESS = 'STAKE_FETCH_POOLS_INFO_SUCCESS';
export const STAKE_FETCH_POOLS_INFO_FAILURE = 'STAKE_FETCH_POOLS_INFO_FAILURE';
