//  fetchBalances
export const VAULT_FETCH_BALANCES_BEGIN = 'VAULT_FETCH_BALANCES_BEGIN';
export const VAULT_FETCH_BALANCES_SUCCESS = 'VAULT_FETCH_BALANCES_SUCCESS';
export const VAULT_FETCH_BALANCES_FAILURE = 'VAULT_FETCH_BALANCES_FAILURE';
//  fetchPoolBalances
export const VAULT_FETCH_POOL_BALANCES_BEGIN = 'VAULT_FETCH_POOL_BALANCES_BEGIN';
export const VAULT_FETCH_POOL_BALANCES_SUCCESS = 'VAULT_FETCH_POOL_BALANCES_SUCCESS';
export const VAULT_FETCH_POOL_BALANCES_FAILURE = 'VAULT_FETCH_POOL_BALANCES_FAILURE';
//  fetchApproval
export const VAULT_FETCH_APPROVAL_BEGIN = 'VAULT_FETCH_APPROVAL_BEGIN';
export const VAULT_FETCH_APPROVAL_SUCCESS = 'VAULT_FETCH_APPROVAL_SUCCESS';
export const VAULT_FETCH_APPROVAL_FAILURE = 'VAULT_FETCH_APPROVAL_FAILURE';
//  fetchDeposit
export const VAULT_FETCH_DEPOSIT_BEGIN = 'VAULT_FETCH_DEPOSIT_BEGIN';
export const VAULT_FETCH_DEPOSIT_SUCCESS = 'VAULT_FETCH_DEPOSIT_SUCCESS';
export const VAULT_FETCH_DEPOSIT_FAILURE = 'VAULT_FETCH_DEPOSIT_FAILURE';
//  fetchClaim
export const VAULT_FETCH_CLAIM_BEGIN = 'VAULT_FETCH_CLAIM_BEGIN';
export const VAULT_FETCH_CLAIM_SUCCESS = 'VAULT_FETCH_CLAIM_SUCCESS';
export const VAULT_FETCH_CLAIM_FAILURE = 'VAULT_FETCH_CLAIM_FAILURE';
//  fetchWithdraw
export const VAULT_FETCH_WITHDRAW_BEGIN = 'VAULT_FETCH_WITHDRAW_BEGIN';
export const VAULT_FETCH_WITHDRAW_SUCCESS = 'VAULT_FETCH_WITHDRAW_SUCCESS';
export const VAULT_FETCH_WITHDRAW_FAILURE = 'VAULT_FETCH_WITHDRAW_FAILURE';
//  fetchFarm
export const VAULT_FETCH_FARM_BEGIN = 'VAULT_FETCH_FARM_BEGIN';
export const VAULT_FETCH_FARM_SUCCESS = 'VAULT_FETCH_FARM_SUCCESS';
export const VAULT_FETCH_FARM_FAILURE = 'VAULT_FETCH_FARM_FAILURE';
//  fetchHarvest
export const VAULT_FETCH_HARVEST_BEGIN = 'VAULT_FETCH_HARVEST_BEGIN';
export const VAULT_FETCH_HARVEST_SUCCESS = 'VAULT_FETCH_HARVEST_SUCCESS';
export const VAULT_FETCH_HARVEST_FAILURE = 'VAULT_FETCH_HARVEST_FAILURE';
//  fetchUniswapPrices
export const VAULT_FETCH_UNISWAP_PRICES_BEGIN = 'VAULT_FETCH_UNISWAP_PRICES_BEGIN';
export const VAULT_FETCH_UNISWAP_PRICES_SUCCESS = 'VAULT_FETCH_UNISWAP_PRICES_SUCCESS';
export const VAULT_FETCH_UNISWAP_PRICES_FAILURE = 'VAULT_FETCH_UNISWAP_PRICES_FAILURE';
