import {govPoolABI} from "./abi";

export const staking = [
    {
        id: 'moo_venus_eth-brew',
        name: 'CafeSwap',
        logo: 'single-assets/ETH.png',
        token: 'mooVenusEth',
        tokenDecimals: 18,
        tokenAddress: '0xA9936272065e6DDAc9D2453C9a2712B581e9aE1B',
        earnedToken: 'BREW',
        earnedTokenDecimals: 18,
        earnedTokenAddress: '0x790Be81C3cA0e53974bE2688cDb954732C9862e1',
        earnContractAddress: '0xC7e3795259e9f74F4F2265Bf28680a70b41B4334',
        earnContractAbi: govPoolABI,
        partnership: true,
        partner: {
            logo: 'stake/cafeswap/cafeswap.png',
            background: 'stake/cafeswap/background.png',
            text: 'CafeSwap is a yield farming and staking platform on BSC Chain, We have chosen BSC because of its low tnx fees and faster speed. We have built this project to provide the best experience with farming while regulating the supply, we believe in partnerships hence we aim to bring all BSC DeFi ecosystems in one place to have a friendly ecosystem for all of us.',
            website: 'https://cafeswap.finance',
            social: {
                telegram: 'https://t.me/CafeSwap',
                twitter: 'https://twitter.com/cafeswapfinance',
            },
        },
    },
    {
        id: 'moo_venus_btc-ramen',
        name: 'RamenSwap',
        logo: 'single-assets/BTCB.svg',
        token: 'mooVenusBtc',
        tokenDecimals: 18,
        tokenAddress: '0x7255Ae13BA4484eD33fB48c4b833000dC12888B4',
        earnedToken: 'RAMEN',
        earnedTokenDecimals: 18,
        earnedTokenAddress: '0x4F47A0d15c1E53F3d94c069C7D16977c29F9CB6B',
        earnContractAddress: '0x07613c90c6f4F4910e53A1A6fF5dAc352C6a16e4',
        earnContractAbi: govPoolABI,
        partnership: true,
        partner: {
            logo: 'stake/ramenswap/ramenswap.png',
            background: 'stake/ramenswap/background.png',
            text: 'The Most Delicious Yield Farm AMM on Binance Smart Chain. RamenSwap Finance is a community driven Yield Farming, DeFi Aggregator and DEX Aggregator on Binance Smart Chain. You can earn RAMEN by staking it on the pool and farming it by providing the liquidity to earn more delicious RAMEN. You can also maximize your return by compounding your token in the vault and connecting several DEX to find the most efficient swapping routes across all platforms that will be released in Q2 to support BSC space.\n',
            website: 'https://ramenswap.finance/',
            social: {
                telegram: 'https://t.me/ramenswap',
                twitter: 'https://twitter.com/ramenswap',
            },
        },
    },
    {
        id: 'moo_auto_cake-salt',
        name: 'SaltSwap',
        logo: 'single-assets/CAKE.png',
        token: 'mooAutoCAKEfixed',
        tokenDecimals: 18,
        tokenAddress: '0xe0B473c0dD6D7Fea5B395c3Ce7ffd4FEF0ab4373',
        earnedToken: 'SALT',
        earnedTokenDecimals: 18,
        earnedTokenAddress: '0x2849b1aE7E04A3D9Bc288673A92477CF63F28aF4',
        earnContractAddress: '0xDda39b0a11de6e0Ebce995D4A065960532EB332E',
        earnContractAbi: govPoolABI,
        partnership: true,
        partner: {
            logo: 'stake/saltswap/saltswap.png',
            background: 'stake/saltswap/background.png',
            text: 'We are a team of experienced software developers and product managers from top tier tech companies (aka the salts) that want to contribute to the BSC DeFi yield farm movement and take it to the next level. Even though we are starting off with a salty yield farm, we will quickly move on to bigger and greater things. We have big plans for the SALT token.\n',
            website: 'https://saltswap.finance/',
            social: {
                telegram: 'https://t.me/saltswap',
                twitter: 'https://twitter.com/saltswap',
            },
        },
    },
]